apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: suite-postgres
  namespace: infra
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: suite
      owner: suite
      secret:
        name: suite-postgres-secret
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "200"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

