apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-arqueologica-backend
  namespace: suite-arqueologica
  labels:
    app: suite-arqueologica-backend
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suite-arqueologica-backend
  template:
    metadata:
      labels:
        app: suite-arqueologica-backend
        version: v1.0.0
    spec:
      containers:
      - name: backend
        image: localhost:5000/suite-arqueologica-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: suite-arqueologica-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: suite-arqueologica-secrets
              key: SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: suite-arqueologica-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: suite-arqueologica-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5 