apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-backend
  labels:
    app.kubernetes.io/name: suite-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: suite-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suite-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            {{- toYaml .Values.env | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
