image:
  repository: registry.local/suite/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

env:
  - name: ENVIRONMENT
    value: production
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: suite-backend
        key: DATABASE_URL
