name: frontend-ci

on:
  push:
    paths:
      - 'frontend-web/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend-web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        working-directory: frontend-web
        run: npm ci
      - name: Lint
        working-directory: frontend-web
        run: |
          npx --yes eslint . || echo "eslint not configured, skipping"
      - name: Build
        working-directory: frontend-web
        env:
          NEXT_PUBLIC_API_URL: /api
          NEXT_PUBLIC_OIDC_ISSUER: https://keycloak.habilispro.com/realms/suite-arqueologica
          NEXT_PUBLIC_OIDC_CLIENT_ID: suite-frontend
        run: npm run build --if-present

